"""Write provenance, source audit summary and inventory; never alters artwork."""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[1]
manifest=json.loads((ROOT/'manifest.json').read_text())
audit={x['id']:x for x in json.loads((ROOT/'source-validation.json').read_text())}
lines=['# Reserve character inventory','','40 character source PNGs generated with the built-in image_gen tool, plus one unsuccessful transparency retry. **Zero sheets currently pass the requested transparent, aligned export requirements.**','','All source images are 1254 × 1254 RGB; 30 have magenta backgrounds and 10 have painted checkerboards. The targeted alpha retry also returned RGB with no transparency. Existing character files are untouched.','','## Review','','Open [animated review](review/index.html). It includes all six allegiance/category groups, state selection, speed, pause, one-shot replay and target-size comparison. Six labeled PNG contact sheets are linked there. The source animation previews use provisional equal subdivisions; visibly cropped weapons, borrowed neighboring pixels and jumps expose the need for frame extraction and alignment. Playback controls passed automated browser checks; animation anatomy and seamlessness are not certified.','','## Asset conventions','','Requested layout matches the original collection: six columns and six rows, idle → movement → attack/casting → hit → stunned → death. Idle, movement and stun loop; other states stop on their last frame in the preview. Ground, airborne and caster prompts differ appropriately. Large independent spell effects/projectiles were excluded; small staff-tip glows may remain in the drawings.','','The original collection did not contain per-frame timing metadata. `manifest.json` supplies explicitly proposed review timings, not established game timings. The 48/64/96-pixel target cells are logical intent; the actual generated source cells are approximately 209 pixels and must not be treated as final game resolution.','','## Outstanding corrections','','- Remove opaque backgrounds while preserving navy outlines, pale armor, wing membranes and internal transparent gaps.','- Extract all poses into uniform cells; stabilize foot/body anchors without normalizing away intentional attack or falling motion.','- Repair frame-to-frame equipment inconsistencies: for example Grave Warden has borrowed sword/shield details in later rows, and Lantern Keeper includes unwanted status marks.','- Review wing anatomy, turn/facing consistency, walk contact, hit reactions and loop seams in each sequence.','- Remove stray pixels and separate any baked status effects. Exact palette/pixel-density and relative-scale cleanup remains necessary.','- No automatic image-cleanup script has been run. Permission for script-based background removal and alignment is pending.','','## Files','','Grid-contact counts below are conservative color-based diagnostics, **not proven clipping counts**. They identify frames needing visual review.','','| Character | Allegiance | Category | Source PNG | Target cell | Potential grid contacts |','| --- | --- | --- | --- | ---: | ---: |']
checks=[]
for x in manifest:
    a=audit[x['id']]
    copy=ROOT/x['file'];source=Path(x['source'])
    digest=hashlib.sha256(copy.read_bytes()).hexdigest()
    checks.append({'id':x['id'],'file':x['file'],'sha256':digest,'originalCopyMatches':digest==hashlib.sha256(source.read_bytes()).hexdigest()})
    lines.append(f"| {x['name']} | {x['allegiance']} | {x['category']} | [{copy.name}]({x['file']}) | {x['cell']} | {a['framesWithPotentialGridContact']} / 36 |")
lines+=['','Full exact prompts and original output paths: [manifest.json](manifest.json). Initial generation specification: [generation-plan.json](generation-plan.json). Read-only pixel diagnostics: [source-validation.json](source-validation.json). Copy hashes: [copy-validation.json](copy-validation.json).','','No runtime source, spawn configuration, automatic asset manifest or loading code was changed.']
(ROOT/'INVENTORY.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
(ROOT/'copy-validation.json').write_text(json.dumps(checks,indent=2)+'\n')
print(f'{len(checks)} source copies checked; all match: {all(x["originalCopyMatches"] for x in checks)}')
